#!/bin/bash

echo "Building yacc..."

bison src/libmonga/grammar.y -d -v -g &&
mv grammar.dot bin/grammar.dot &&
mv grammar.output bin/grammar.output &&
mv grammar.tab.c bin/gensrc/grammar.tab.c &&
mv grammar.tab.h bin/gensrc/grammar.tab.h &&
exit 0

exit 1