#!/bin/bash

#####################################################

# Executable source files
SRC_FILES="src/exec/*.c"

BASE_COMPILER_ARGS="-Wall -Wextra -Werror -Ibin/builds/libmonga/include"

### DEBUG
# Library path
DEBUG_LIB_PATH="bin/builds/libmonga/debug"

# Path to build the executable
DEBUG_OUT_PATH="bin/builds/monga/debug"

# Compilation args
DEBUG_COMPILER_ARGS="-O1 -g"

### RELEASE
# Library path
RELEASE_LIB_PATH="bin/builds/libmonga/release"

# Path to build the executable
RELEASE_OUT_PATH="bin/builds/monga/release"

# Compilation args
RELEASE_COMPILER_ARGS="-O2 -DNDEBUG"

#####################################################

./buildlib &&
gcc -L$DEBUG_LIB_PATH -o $DEBUG_OUT_PATH/monga $SRC_FILES $BASE_COMPILER_ARGS $DEBUG_COMPILER_ARGS -lmonga -lfl -ly
gcc -L$RELEASE_LIB_PATH -o $RELEASE_OUT_PATH/monga $SRC_FILES $BASE_COMPILER_ARGS $RELEASE_COMPILER_ARGS -lmonga -lfl -ly
