#!/bin/bash

#####################################################

# Path to build the executable
OUT_PATH="bin/builds/monga"

# Executable source files
SRC_FILES="src/exec/*.c"

# Compilation args
COMPILER_ARGS="-Wall -Ibin/builds/libmonga/include"

# Library path
LIB_PATH="bin/builds/libmonga"

#####################################################

./buildlib &&
gcc -L$LIB_PATH -o $OUT_PATH/monga $SRC_FILES $COMPILER_ARGS -lmonga -lfl -ly
