#!/bin/bash

#####################################################

# Path to library source code root
SRC_PATH="src/libmonga"

# Path to folder containing library headers meant to be exported to the build directory
EXPORT_HEADERS_PATH=$SRC_PATH/include

# Path to LEX/YACC generated source code
GEN_SRC_PATH="bin/gensrc"

# Path to create the monga lib
OUT_PATH="bin/builds/libmonga"

# Extra arguments passed to the compiler
COMPILER_ARGS="-Wall -Wextra -I$GEN_SRC_PATH -I$EXPORT_HEADERS_PATH -I$SRC_PATH -DMON_COMPILING_LIB"

#####################################################

./buildlex &&
./buildyacc &&
echo "Building library..."

# generate object files
for file in $(find $SRC_PATH -name "*.c"); do
	echo "Compiling $file..."
	gcc $COMPILER_ARGS -fpic -c $file
done
for file in $GEN_SRC_PATH/*.c; do
	echo "Compiling $file..."
	gcc $COMPILER_ARGS -fpic -c $file
done

wait

# add them to single string to be fed into gcc
objects=""
for file in "./*.o"; do
	objects+=" $file"
done

# generate library
rm $OUT_PATH/libmonga.a
ar rcs $OUT_PATH/libmonga.a $objects

# remove object files
for o in $objects; do
	rm $o
done

# copy headers from source path to build/include and delete previous ones
rm -R $OUT_PATH/include
cp -R $EXPORT_HEADERS_PATH $OUT_PATH/include