#!/bin/bash

echo "Building yacc..."

bison src/monga.y -d -v -g &&
mv monga.dot bin/monga.dot &&
mv monga.output bin/monga.output &&
mv monga.tab.c bin/monga.tab.c &&
mv monga.tab.h bin/include/monga.tab.h &&
exit 0

exit 1