#!/bin/bash

# Generate missing '.expected' files for test cases by running monga.
# Make sure to read them and correct errors manually.
# Usage:
#	gencases <PATH_TO_MONGA_EXECUTABLE>

MONGA_EXEC_PATH=$1
shift

function gen_cases_monga {
	for f in $2/*; do
		[ -e "$f" ] || continue

		if [[ $f == *.expected ]]; 	then
			# Ignore reference files
			continue
		fi

		if [ -f "$f.expected" ]; then
			# Ignore files that already have a reference
			continue
		fi

		if [ -d $f ]; then
			$MONGA_EXEC_PATH $1 $f/* > $f.expected 2>&1
		else
			$MONGA_EXEC_PATH $1 $f > $f.expected 2>&1
		fi
		
	done
}

gen_cases_monga -s tests/sem_test_cases
gen_cases_monga -r tests/reduce_dump_cases
gen_cases_monga -p tests/ast_dump_cases
gen_cases_monga -l tests/lex_cases

# Executable outputs work differently -- we need to test
# the output of the generated program, not only monga's output.
for f in tests/codegen_cases/*.mon; do
	[ -e "$f" ] || continue

	if [ -f "$f.expected" ]; then
		# Ignore files that already have a reference
		continue
	fi

	rm $f.ll &>/dev/null

	scripts/bash/testcgen $MONGA_EXEC_PATH $f > $f.expected
done