#!/bin/bash

cd tests
MONGA_EXEC_PATH="../bin/src/exec/monga"

function gen_cases {
	for f in $2/*; do
		[ -e "$f" ] || continue

		if [[ $f == *.expected ]]; 	then
			# Ignore reference files
			continue
		fi

		if [ -f "$f.expected" ]; then
			# Ignore files that already have a reference
			continue
		fi

		if [ -d $f ]; then
			$MONGA_EXEC_PATH $1 $f/* > $f.expected 2>&1
		else
			$MONGA_EXEC_PATH $1 $f > $f.expected 2>&1
		fi
		
	done
}

gen_cases -s sem_test_cases
gen_cases -r reduce_dump_cases
gen_cases -p ast_dump_cases
gen_cases -l lex_cases
